const i18n = {
  jp: {
    heroes: {
      achates: 'アカテス',
      adlay: 'アドレー',
      ains: 'エインズ',
      aither: 'アイテール',
      alencia: 'Alencia',
      alexa: 'アレクサ',
      all_rounder_wanda: 'All-Rounder Wanda',
      ambitious_tywin: 'Ambitious Tywin',
      angelic_montmorancy: '守護天使 モンモランシー',
      angelica: 'アンジェリカ',
      apocalypse_ravi: '黙示録 ラヴィ',
      aramintha: 'アラミンタ',
      arbiter_vildred: '執行人 ヴィルドレッド',
      armin: 'アーミン',
      arowell: 'アロウェル',
      assassin_cartuja: '暗幕殺法 カルトゥハ',
      assassin_cidd: '暗殺者 シダー',
      assassin_coli: '静寂のコリー',
      auxiliary_lots: '戮力のラッツ',
      azalea: 'アゼリア',
      baal_and_sezan: 'バアル＆セザン',
      baiken: '梅喧',
      basar: 'バサール',
      bask: 'バスク',
      batisse: 'バータス',
      bellona: 'ヴェローナ',
      benevolent_romann: 'Benevolent Romann',
      blaze_dingo: '焼尽のディンゴ',
      blood_blade_karin: '血剣のカリン',
      butcher_corps_inquisitor: 'エクスキューショナー',
      captain_rikoris: '先遣部隊長 リコリス',
      carmainerose: 'カーマイン・ローズ',
      carrot: 'キャロット',
      cartuja: 'カルトゥハ',
      cecilia: 'セシリア',
      celeste: 'セレスト',
      celestial_mercedes: '天穹のメルセデス',
      cermia: 'チェルミア',
      challenger_dominiel: '挑戦者 ドミニエル',
      champion_zerato: '勝負師 ゼラト',
      chaos_inquisitor: 'カオス教団 追跡者',
      chaos_sect_axe: 'カオス教団 重斧総長',
      charles: 'チャールズ',
      charlotte: 'シャルロッテ',
      chloe: 'クロエ',
      church_of_ilryos_axe: 'イリオス教団 斧兵',
      cidd: '暗殺者 シダー',
      clarissa: 'クラリッサ',
      coli: 'コリー',
      commander_lorina: '指揮官 ロリーナ',
      corvus: 'コルヴス',
      crescent_moon_rin: '三日月のリン',
      crimson_armin: '紅焔のアーミン',
      crozet: '暴徒 クロゼ',
      dark_corvus: '破壊者 コルヴス',
      desert_jewel_basar: '砂漠の宝石 バサール',
      destina: 'デスティーナ',
      diene: 'ディエネ',
      dingo: 'ディンゴ',
      dizzy: 'ディズィー',
      dominiel: 'ドミニエル',
      doris: 'ドリス',
      eaton: 'イートン',
      elena: 'Elena',
      elson: 'エルソン',
      enott: 'エノット',
      faithless_lidica: 'Failthless Lidica',
      falconer_kluri: '鷹狩のクルリ',
      fallen_cecilia: 'セシリア',
      fighter_maya: '戦闘人形 マヤ',
      furious: 'フューリオス',
      general_purrgis: '勇将 ファジス',
      gloomyrain: 'グルーミー・レイン',
      guider_aither: '求道者 アイテール',
      gunther: 'ギュンター',
      hataan: 'ハタン',
      haste: 'ヘイスト',
      hazel: 'ヘイゼル',
      helga: 'ヘルガ',
      hurado: 'ヒュラド',
      iseria: 'イセリア',
      jecht: 'ジェクト',
      jena: 'ジェナ',
      judge_kise: '審判者 キセ',
      judith: 'ジュディス',
      karin: 'カリン',
      kayron: 'カイロン',
      ken: 'ケン',
      khawana: 'Khawana',
      khawazu: 'カワヅ',
      kiris: 'キリス',
      kise: 'キセ',
      kitty_clarissa: '飼い猫 クラリッサ',
      kluri: 'クルリ',
      krau: 'クラウ',
      lena: 'レナ',
      leo: 'レオ',
      lidica: 'リディカ',
      lilias: 'リリアス',
      lilibet: 'リリベット',
      lorina: 'ロリーナ',
      lots: 'ラッツ',
      ludwig: 'ルートヴィヒ',
      luluca: 'ルルカ',
      luna: 'ルナ',
      maid_chloe: 'メイド クロエ',
      martial_artist_ken: '覇者 ケン',
      mascot_hazel: '生徒会広報 ヘイゼル',
      maya: 'マヤ',
      melissa: 'メリッサ',
      mercedes: 'メルセデス',
      mirsa: 'ミルサ',
      mistychain: 'ミスティー・チェイン',
      montmorancy: 'モンモランシー',
      mucacha: 'ムカチャ',
      nemunas: 'ネムナス',
      otillie: 'オティーリエ',
      pearlhorizon: 'パール・ホライゾン',
      purrgis: 'ファジス',
      pyllis: 'ピィリス',
      ras: 'ラス',
      ravi: 'ラヴィ',
      requiemroar: 'レクイエム・ロア',
      researcher_carrot: '研究者 キャロット',
      righteous_thief_roozid: '義賊のルージッド',
      rikoris: 'リコリス',
      rima: 'リマ',
      rin: 'リン',
      roaming_warrior_leo: 'さすらいの戦士 レオ',
      romann: 'ローマン',
      roozid: 'ルージット',
      rose: 'ロゼ',
      ruele_of_light: '神光のルエル',
      sage_baal_and_sezan: '賢者 バアル＆セザン',
      schuri: 'シュリ',
      shooting_star_achates: '流れ星☆アカテス',
      seaside_bellona: '浜辺のヴェローナ',
      serila: 'セリラ',
      sez: 'セズ',
      shadow_rose: '暗躍のロゼ',
      sigret: 'セクレット',
      silk: 'シルク',
      silver_blade_aramintha: '白銀のアラミンタ',
      sol: 'ソル',
      specimen_sez: '実験体 セズ',
      specter_tenebria: '幻影のテネブレア',
      surin: 'スーリン',
      sven: 'スヴェン',
      tamarinne: 'ルリ',
      taranor_guard: 'タラノル近衛隊員',
      taranor_royal_guard: 'タラノル王宮衛兵',
      tenebria: 'テネブレア',
      tieria: 'ディエリア',
      troublemaker_crozet: '暴徒 クロゼ',
      tywin: 'タイウィン',
      vildred: 'ヴィルドレッド',
      violet: 'ヴィオレタ',
      vivian: 'ビビアン',
      wanda: 'ワンダ',
      wanderer_silk: '流浪者 シルク',
      watcher_schuri: '監視者 シュリ',
      yufine: 'ユピネ',
      yuna: 'ユナ',
      zeno: 'ゼノ',
      zerato: 'ゼラト',
    },
    artifacts: {
      no_proc: 'No Artifact Proc',
      border_coin: '天命の金貨',
      daydream_joker: '白昼夢の道化師',
      draco_plate: 'ドラゴニックプレート',
      exorcist_tonfa: '闘鬼の戦具',
      elyha_knife: 'エリハの短剣',
      hell_cutter: '地獄のチェーンソー',
      iron_fan: '高貴なる鉄扇',
      kaladra: 'カルラドラ',
      portrait_of_the_saviors: 'イエラのバイオリン',
      otherworldly_machinery: '異世界の機械',
      reingar_special_drink: 'レインガル特製ドリンク',
      sigurd_scythe: 'シグルの大鎌',
      sword_of_the_morning: '黎明の剣',
      uberius_tooth: 'ユーベリウスの牙',
      wind_rider: '旋風の操手',
    },
    form: {
      nb_targets: 'Number of enemies',
      nb_hits: 'Number of hits',
      target_max_hp: 'Targets\'s Max HP',
      target_hp_pc: 'Targets\'s HP %',
      target_hp: 'Targets\'s HP',
      target_speed: 'Targets\'s Speed',
      target_nb_buff: 'Buffs on Targets',
      target_nb_debuff: 'Debuffs on Targets',
      target_has_buff: 'Target has buffs',
      target_has_debuff: 'Target has debuffs',
      target_has_bleed: 'Target has Bleed',
      target_has_sleep: 'Target has Sleep',
      target_is_stunned: 'Target is stunned',
      target_has_barrier: 'Target has Barrier',
      target_magic_nailed: 'Magic Nail on Target',
      target_nb_bleed: 'Number of Bleed on target',
      target_bleed_detonate: 'Bleed effects to Detonate',
      target_burn_detonate: 'Burn effects to Detonate',
      caster_max_hp: 'Caster\'s Max HP',
      caster_hp_pc: 'Caster\'s HP %',
      caster_hp: 'Caster\'s HP',
      caster_hp_above_50pc: 'Caster\'s HP above 50%',
      caster_defense: 'Caster\'s Defense',
      caster_defense_up: 'Increased Defense',
      caster_speed: 'Caster\'s Speed',
      caster_speed_up: 'Increased Speed',
      caster_nb_buff: 'Buffs on Caster',
      caster_full_focus: 'Full Focus',
      caster_nb_focus: 'Focus',
      caster_fighting_spirit: 'Fighting Spirit',
      caster_invincible: 'Caster is Invincible',
      caster_vigor: 'Caster has Vigor',
      caster_enrage: 'Caster has Rage',
      caster_stealth: 'Caster has Stealth',
      stack_crit_hit: 'Crit Hit Stack',
      non_attack_skill_stack_10: 'Non-Attack Skill Stack',
      attack_skill_stack_5: 'Attack Stack',
      non_attack_skill_stack_3: 'Non-Attack Skill Stack',
      turn_stack: 'Turn Stack',
      dead_people: 'People who died',
      highest_ally_attack: 'Highest Ally Attack',
      ally_atk_up: 'Ally has Increased Attack',
      ally_atk_up_great: 'Ally has Increased Attack (Great)',
      skill_tree_completed: 'Skill Tree Completed',
      s3_stack: 'S3 Stack',
      all_allies_fire: 'All Allies Fire',
      exclusive_equipment_1: 'Exclusive Equipment #1',
      exclusive_equipment_2: 'Exclusive Equipment #2',
      exclusive_equipment_3: 'Exclusive Equipment #3',
    },
    skills: {
      s1: 's1',
      s2: 's2',
      s3: 's3',
    }
  },
  zh: {
    heroes: {
      achates: '雅卡泰絲',
      adlay: '亞迪賴',
      ains: '艾因茲',
      aither: '埃德勒',
      alencia: '艾蓮西雅',
      alexa: '雅莉莎',
      all_rounder_wanda: '疑難雜症專家汪達',
      ambitious_tywin: '野心份子泰溫',
      angelic_montmorancy: '守護天使蒙茉朗西',
      angelica: '安潔莉卡',
      apocalypse_ravi: '末日蘿菲',
      aramintha: '雅拉敏塔',
      arbiter_vildred: '執行官維德瑞',
      armin: '亞敏',
      arowell: '雅洛薇',
      assassin_cartuja: '殺手卡爾圖哈',
      assassin_cidd: '殺手席德',
      assassin_coli: '殺手可麗',
      auxiliary_lots: '輔助型拉茲',
      azalea: '亞潔理亞',
      baal_and_sezan: '巴爾&塞尚',
      baiken: '梅喧',
      basar: '巴薩爾',
      bask: '巴思克',
      batisse: '巴托斯',
      bellona: '維爾蘿娜',
      benevolent_romann: '仁慈的洛曼',
      blaze_dingo: '烈火汀果',
      blood_blade_karin: '血劍卡琳',
      butcher_corps_inquisitor: '混沌教屠殺追擊者',
      captain_rikoris: '先鋒隊長里科黎司',
      carmainerose: '卡麥蘿茲',
      carrot: '卡蘿',
      cartuja: '卡爾圖哈',
      cecilia: '賽西莉亞',
      celeste: '賽雷斯特',
      celestial_mercedes: '外太空的玫勒賽德絲',
      cermia: '潔若米亞',
      challenger_dominiel: '挑戰者多米妮爾',
      champion_zerato: '終結者杰拉圖',
      chaos_inquisitor: '屠殺部隊員',
      chaos_sect_axe: '混沌教巨斧大將軍',
      charles: '查爾斯',
      charlotte: '夏綠蒂',
      chloe: '克蘿愛',
      church_of_ilryos_axe: '伊利歐斯教斧兵',
      cidd: '席德',
      clarissa: '克萊莉莎',
      coli: '可麗',
      commander_lorina: '指揮官蘿里娜',
      corvus: '科爾布思',
      crescent_moon_rin: '新月舞姬鈴兒',
      crimson_armin: '紅焰亞敏',
      crozet: '克羅澤',
      dark_corvus: '黑暗的科爾布思',
      desert_jewel_basar: '沙漠寶石巴薩爾',
      destina: '戴絲蒂娜',
      diene: '迪埃妮',
      dingo: '汀果',
      dizzy: '蒂姬',
      dominiel: '多米妮爾',
      doris: '朵莉思',
      eaton: '伊頓',
      elena: '艾蕾娜',
      elson: '艾爾森',
      enott: '艾諾特',
      faithless_lidica: '無神論者麗迪卡',
      falconer_kluri: '鷹獵人可露莉',
      fallen_cecilia: '墮落的賽西莉亞',
      fighter_maya: '戰鬥型瑪雅',
      furious: '尤貝烏斯',
      general_purrgis: '大將法濟斯',
      gloomyrain: '格魯美蘭',
      guider_aither: '求道者埃德勒',
      gunther: '坤特',
      hataan: '哈坦',
      haste: '海斯特',
      hazel: '海茲',
      helga: '赫爾嘉',
      hurado: '修拉杜',
      iseria: '伊賽麗亞',
      jecht: '傑克托',
      jena: '捷娜',
      judge_kise: '審判者綺世',
      judith: '茱迪絲',
      karin: '卡琳',
      kayron: '凱隆',
      ken: '肯恩',
      khawana: '卡瓦娜',
      khawazu: '卡瓦朱',
      kikirat_v2: '奇奇拉特V.2',
      kiris: '奇麗絲',
      kise: '綺世',
      kitty_clarissa: '貓咪克萊莉莎',
      kluri: '可露莉',
      krau: '克勞烏',
      lena: '雷娜',
      leo: '雷歐',
      lidica: '麗迪卡',
      lilias: '莉莉亞斯',
      lilibet: '莉莉貝',
      lorina: '蘿里娜',
      lots: '拉茲',
      ludwig: '魯特比',
      luluca: '璐璐卡',
      luna: '露娜',
      maid_chloe: '僕人克蘿愛',
      martial_artist_ken: '武鬥家肯恩',
      mascot_hazel: '吉祥物海茲',
      maya: '瑪雅',
      melissa: '梅麗莎',
      mercedes: '玫勒賽德絲',
      mirsa: '米勒莎',
      mistychain: '美絲緹彩',
      montmorancy: '蒙茉朗西',
      mucacha: '穆卡察',
      nemunas: '尼姆拉斯',
      otillie: '奧緹莉爾',
      pearlhorizon: '波蘿萊珍',
      purrgis: '法濟斯',
      pyllis: '費莉絲',
      ras: '拉斯',
      ravi: '蘿菲',
      requiemroar: '雷奎姆洛',
      researcher_carrot: '研究者卡蘿',
      righteous_thief_roozid: '義賊魯茲德',
      rikoris: '里科黎司',
      rima: '黎瑪',
      rin: '鈴兒',
      roaming_warrior_leo: '流浪勇士雷歐',
      romann: '洛曼',
      roozid: '魯茲德',
      rose: '蘿季',
      ruele_of_light: '光之瑞兒',
      sage_baal_and_sezan: '賢者巴爾&塞尚',
      schuri: '修里',
      shooting_star_achates: '流星雅卡泰絲',
      seaside_bellona: '海邊的維爾蘿娜',
      serila: '塞麗拉',
      sez: '賽茲',
      shadow_rose: '暗影蘿季',
      sigret: '賽珂蘭特',
      silk: '席可',
      silver_blade_aramintha: '白銀刀刃的雅拉敏塔',
      sol: '索爾',
      specimen_sez: '實驗體賽茲',
      specter_tenebria: '幻影的泰妮布里雅',
      surin: '蘇琳',
      sven: '史賓',
      tamarinne: '塔瑪林爾',
      taranor_guard: '塔拉諾爾禁衛隊員',
      taranor_royal_guard: '塔拉諾爾王宮士兵',
      tenebria: '泰妮布里雅',
      tieria: '黛莉亞',
      troublemaker_crozet: '不法之徒克羅澤',
      tywin: '泰溫',
      vildred: '維德瑞',
      violet: '菲奧雷托',
      vivian: '薇薇安',
      wanda: '汪達',
      wanderer_silk: '流浪者席可',
      watcher_schuri: '注視者修里',
      yufine: '優芬妮',
      yuna: '尤娜',
      zeno: '傑諾',
      zerato: '杰拉圖',
    },
    artifacts: {
      no_proc: '無神器',
      border_coin: '孤注一擲',
      daydream_joker: '白日夢小丑',
      draco_plate: '龍族板甲',
      exorcist_tonfa: '鬥鬼的拐棍',
      elyha_knife: '埃里哈刀',
      hell_cutter: '地獄切割機',
      iron_fan: '鐵扇',
      kaladra: '嘉拉特拉',
      portrait_of_the_saviors: '救援者們的畫像',
      otherworldly_machinery: '異界的機械',
      reingar_special_drink: '雷茵格爾特調飲料',
      sigurd_scythe: '席格勒賽斯',
      sword_of_the_morning: '黎明劍',
      uberius_tooth: '尤貝里烏斯的臼齒',
      wind_rider: '乘風者',
    },
    form: {
      nb_targets: '敵人數量',
      nb_hits: '攻擊次數',
      target_max_hp: '目標最大生命值',
      target_hp_pc: '目標當前生命值',
      target_hp: '目標當前生命值',
      target_speed: '目標速度',
      target_nb_buff: '目標强化效果數量',
      target_nb_debuff: '目標弱化效果數量',
      target_has_buff: '目標有强化效果',
      target_has_debuff: '目標有弱化效果',
      target_has_bleed: '目標為出血狀態',
      target_has_sleep: '目標為睡眠狀態',
      target_is_stunned: '目標為眩暈狀態',
      target_has_barrier: '目標有防護罩',
      target_magic_nailed: '目標有魔法釘',
      target_nb_bleed: '目標的出血效果數量',
      target_bleed_detonate: '出血效果 激爆',
      target_burn_detonate: '燒傷效果 激爆',
      caster_max_hp: '自身最大生命值',
      caster_hp_pc: '自身當前生命值',
      caster_hp: '自身當前生命值',
      caster_hp_above_50pc: '自身當前生命值>50%',
      caster_defense: '自身防禦力',
      caster_defense_up: '防禦力增加效果',
      caster_speed: '自身速度',
      caster_speed_up: '速度提升效果',
      caster_nb_buff: '自身强化效果數量',
      caster_full_focus: '專注力最大值',
      caster_nb_focus: '專注力',
      caster_fighting_spirit: '鬥志',
      caster_invincible: '自身無敵狀態',
      caster_vigor: '自身魄力狀態',
      caster_enrage: '自身激怒狀態',
      caster_stealth: '自身隱身狀態',
      stack_crit_hit: '暴擊叠加數',
      non_attack_skill_stack_10: '非攻擊技能叠加數',
      attack_skill_stack_5: '攻擊叠加數',
      non_attack_skill_stack_3: '非攻擊技能叠加數',
      turn_stack: '回合叠加數',
      dead_people: '死亡人數',
      highest_ally_attack: '我軍最高攻擊力',
      ally_atk_up: '目標我軍攻擊力增加',
      ally_atk_up_great: '目標我軍攻擊力增加 (大幅)',
      skill_tree_completed: '技能樹滿覺醒',
      s3_stack: '三技能叠加數',
      all_allies_fire: '全體我軍為火屬性',
      exclusive_equipment_1: '專屬裝備 #1',
      exclusive_equipment_2: '專屬裝備 #2',
      exclusive_equipment_3: '專屬裝備 #3',
    },
    skills: {
      non_applicable: '無',
      s1: '一技能',
      s2: '二技能',
      s3: '三技能',
      s1_soulburn: '一技能 靈魂燃燒',
      s2_soulburn: '二技能 靈魂燃燒',
      s3_soulburn: '三技能 靈魂燃燒',
    }
  }
};

const heroName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return heroes[id].name;
  } else {
    return i18n[lang].heroes[id] || heroes[id].name;
  }
};

const artifactName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return artifacts[id] ? artifacts[id].name : 'No Artifact Proc';
  } else {
    return i18n[lang].artifacts[id] || artifacts[id].name;
  }
};

const formLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return elements[id].label;
  } else {
    return i18n[lang].form[id] || elements[id].label;
  }
};

const skillLabel = (id, soulburn = false) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return (id === 'non_applicable') ? 'n/a' : id.toUpperCase() + (soulburn ? ' Soulburn' : '');
  } else {
    id = soulburn ? id+'_soulburn' : id;
    return i18n[lang].skills[id] || id.toUpperCase();
  }
};