const i18n = {
  en: {
    nicknames: {
      achates: '',
      adlay: '',
      ains: '',
      aither: '',
      alencia: '',
      alexa: '',
      all_rounder_wanda: '',
      ambitious_tywin: '',
      angelic_montmorancy: 'momo',
      angelica: '',
      apocalypse_ravi: '',
      aramintha: '',
      arbiter_vildred: 'arby',
      armin: '',
      arowell: '',
      assassin_cartuja: 'fatcat',
      assassin_cidd: 'a.cidd accid',
      assassin_coli: 'a.coli acoli',
      auxiliary_lots: 'a.lots alots',
      azalea: '',
      baal_and_sezan: '',
      baiken: '',
      basar: '',
      bask: '',
      batisse: '',
      bellona: '',
      benevolent_romann: 'broman',
      blaze_dingo: '',
      blood_blade_karin: 'bbk',
      butcher_corps_inquisitor: '',
      captain_rikoris: '',
      carmainerose: '',
      carrot: '',
      cartuja: '',
      cecilia: '',
      celeste: '',
      celestial_mercedes: '',
      cermia: '',
      challenger_dominiel: 'c.dom cdom',
      champion_zerato: 'c.zerato czerato',
      chaos_inquisitor: '',
      chaos_sect_axe: '',
      charles: '',
      charlotte: '',
      chloe: '',
      church_of_ilryos_axe: 'axe god axegod',
      cidd: '',
      clarissa: '',
      coli: '',
      commander_lorina: '',
      corvus: '',
      crescent_moon_rin: 'ml.rin mlrin',
      crimson_armin: 'c.armin carmin',
      crozet: '',
      dark_corvus: 'dc DC',
      desert_jewel_basar: 'dj.basar djbasar',
      destina: '',
      diene: '',
      dingo: '',
      dizzy: '',
      dominiel: '',
      doris: '',
      eaton: '',
      elena: '',
      elson: '',
      enott: '',
      faithless_lidica: 'f.lidica flidica',
      falconer_kluri: 'f.kluri fkluri',
      fallen_cecilia: 'f.cc fcc',
      fighter_maya: 'f.maya fmaya',
      furious: '',
      general_purrgis: 'g.purrgis gpurrgis',
      gloomyrain: '',
      guider_aither: '',
      gunther: '',
      hataan: '',
      haste: '',
      hazel: '',
      helga: '',
      hurado: '',
      iseria: '',
      jecht: '',
      jena: '',
      judge_kise: 'j.kise jkise',
      judith: '',
      karin: '',
      kayron: '',
      ken: '',
      khawana: '',
      khawazu: '',
      kiris: '',
      kise: '',
      kitty_clarissa: '',
      kluri: '',
      krau: '',
      lena: '',
      leo: '',
      lidica: '',
      lilias: '',
      lilibet: '',
      lorina: '',
      lots: '',
      ludwig: '',
      luluca: '',
      luna: '',
      maid_chloe: 'ml.chloe mlchloe',
      martial_artist_ken: 'ml.ken mlken',
      mascot_hazel: '',
      maya: '',
      melissa: '',
      mercedes: '',
      mirsa: '',
      mistychain: '',
      montmorancy: '',
      mucacha: '',
      nemunas: '',
      otillie: '',
      pearlhorizon: '',
      purrgis: '',
      pyllis: '',
      ras: '',
      ravi: '',
      requiemroar: '',
      researcher_carrot: '',
      righteous_thief_roozid: '',
      rikoris: '',
      rima: '',
      rin: '',
      roaming_warrior_leo: '',
      roana: '',
      romann: '',
      roozid: '',
      rose: '',
      ruele_of_light: '',
      sage_baal_and_sezan: 'ml.baal mlbaal',
      schuri: '',
      shooting_star_achates: 'ssa',
      seaside_bellona: 'ssb',
      serila: '',
      sez: '',
      shadow_rose: '',
      sigret: '',
      silk: '',
      silver_blade_aramintha: 'ml.aramintha mlaramintha',
      sinful_angelica: 'ml.angelica mlangelica',
      sol: '',
      specimen_sez: 'ml.sez mlsez',
      specter_tenebria: 'specte ml.tenebria mltenebria',
      surin: '',
      sven: '',
      tamarinne: '',
      taranor_guard: 'tg',
      taranor_royal_guard: '',
      tenebria: '',
      tieria: '',
      troublemaker_crozet: 'ml.crozet mlcrozet',
      tywin: '',
      vildred: '',
      violet: '',
      vivian: '',
      wanda: '',
      wanderer_silk: 'ml.silk mlsilk',
      watcher_schuri: '',
      yufine: '',
      yuna: '',
      zeno: '',
      zerato: '',
    }
  },
  jp: {
    heroes: {
      achates: 'アカテス',
      adlay: 'アドレー',
      ains: 'エインズ',
      aither: 'アイテール',
      alencia: 'アレンシア',
      alexa: 'アレクサ',
      all_rounder_wanda: '万能解決士 ワンダ',
      ambitious_tywin: '野心家 タイウィン',
      angelic_montmorancy: '守護天使 モンモランシー',
      angelica: 'アンジェリカ',
      apocalypse_ravi: '黙示録 ラヴィ',
      aramintha: 'アラミンタ',
      arbiter_vildred: '執行人 ヴィルドレッド',
      armin: 'アーミン',
      arowell: 'アロウェル',
      assassin_cartuja: '暗幕殺法 カルトゥハ',
      assassin_cidd: '暗殺者 シダー',
      assassin_coli: '静寂のコリー',
      auxiliary_lots: '戮力のラッツ',
      azalea: 'アゼリア',
      baal_and_sezan: 'バアル＆セザン',
      baiken: '梅喧',
      basar: 'バサール',
      bask: 'バスク',
      batisse: 'バータス',
      bellona: 'ヴェローナ',
      benevolent_romann: '忠義者 ローマン',
      blaze_dingo: '焼尽のディンゴ',
      blood_blade_karin: '血剣のカリン',
      butcher_corps_inquisitor: 'エクスキューショナー',
      captain_rikoris: '先遣部隊長 リコリス',
      carmainerose: 'カーマイン・ローズ',
      carrot: 'キャロット',
      cartuja: 'カルトゥハ',
      cecilia: 'セシリア',
      celeste: 'セレスト',
      celestial_mercedes: '天穹のメルセデス',
      cerise: 'セリス',
      cermia: 'チェルミア',
      challenger_dominiel: '挑戦者 ドミニエル',
      champion_zerato: '勝負師 ゼラト',
      chaos_inquisitor: 'カオス教団 追跡者',
      chaos_sect_axe: 'カオス教団 重斧総長',
      charles: 'チャールズ',
      charlotte: 'シャルロッテ',
      chloe: 'クロエ',
      church_of_ilryos_axe: 'イリオス教団 斧兵',
      cidd: '暗殺者 シダー',
      clarissa: 'クラリッサ',
      coli: 'コリー',
      commander_lorina: '指揮官 ロリーナ',
      corvus: 'コルヴス',
      crescent_moon_rin: '三日月のリン',
      crimson_armin: '紅焔のアーミン',
      crozet: '暴徒 クロゼ',
      dark_corvus: '破壊者 コルヴス',
      desert_jewel_basar: '砂漠の宝石 バサール',
      destina: 'デスティーナ',
      diene: 'ディエネ',
      dingo: 'ディンゴ',
      dizzy: 'ディズィー',
      dominiel: 'ドミニエル',
      doris: 'ドリス',
      eaton: 'イートン',
      elena: 'エレナ',
      elson: 'エルソン',
      enott: 'エノット',
      faithless_lidica: '不信者リディカ',
      falconer_kluri: '鷹狩のクルリ',
      fallen_cecilia: 'セシリア',
      fighter_maya: '戦闘人形 マヤ',
      furious: 'フューリオス',
      general_purrgis: '勇将 ファジス',
      gloomyrain: 'グルーミー・レイン',
      guider_aither: '求道者 アイテール',
      gunther: 'ギュンター',
      hataan: 'ハタン',
      haste: 'ヘイスト',
      hazel: 'ヘイゼル',
      helga: 'ヘルガ',
      hurado: 'ヒュラド',
      iseria: 'イセリア',
      jecht: 'ジェクト',
      jena: 'ジェナ',
      judge_kise: '審判者 キセ',
      judith: 'ジュディス',
      karin: 'カリン',
      kawerik: 'カーウェリック',
      kayron: 'カイロン',
      ken: 'ケン',
      khawana: 'カワナ',
      khawazu: 'カワヅ',
      kikirat_v2: 'キキラトV.2',
      kiris: 'キリス',
      kise: 'キセ',
      kitty_clarissa: '飼い猫 クラリッサ',
      kluri: 'クルリ',
      krau: 'クラウ',
      lena: 'レナ',
      leo: 'レオ',
      lidica: 'リディカ',
      lilias: 'リリアス',
      lilibet: 'リリベット',
      little_queen_charlotte: '若き女王 シャルロッテ',
      lorina: 'ロリーナ',
      lots: 'ラッツ',
      ludwig: 'ルートヴィヒ',
      luluca: 'ルルカ',
      luna: 'ルナ',
      maid_chloe: 'メイド クロエ',
      martial_artist_ken: '覇者 ケン',
      mascot_hazel: '生徒会広報 ヘイゼル',
      maya: 'マヤ',
      melissa: 'メリッサ',
      mercedes: 'メルセデス',
      mercenary_helga: '自由な傭兵 ヘルガ',
      mirsa: 'ミルサ',
      mistychain: 'ミスティー・チェイン',
      montmorancy: 'モンモランシー',
      mucacha: 'ムカチャ',
      nemunas: 'ネムナス',
      otillie: 'オティーリエ',
      pavel: 'パベル',
      pearlhorizon: 'パール・ホライゾン',
      purrgis: 'ファジス',
      pyllis: 'ピィリス',
      ras: 'ラス',
      ravi: 'ラヴィ',
      requiemroar: 'レクイエム・ロア',
      researcher_carrot: '研究者 キャロット',
      righteous_thief_roozid: '義賊のルージッド',
      rikoris: 'リコリス',
      rima: 'リマ',
      rin: 'リン',
      roaming_warrior_leo: 'さすらいの戦士 レオ',
      romann: 'ローマン',
      roozid: 'ルージット',
      rose: 'ロゼ',
      ruele_of_light: '神光のルエル',
      sage_baal_and_sezan: '賢者 バアル＆セザン',
      schuri: 'シュリ',
      shooting_star_achates: '流れ星☆アカテス',
      seaside_bellona: '浜辺のヴェローナ',
      serila: 'セリラ',
      sez: 'セズ',
      shadow_rose: '暗躍のロゼ',
      sigret: 'セクレット',
      silk: 'シルク',
      silver_blade_aramintha: '白銀のアラミンタ',
      sol: 'ソル',
      specimen_sez: '実験体 セズ',
      specter_tenebria: '幻影のテネブレア',
      surin: 'スーリン',
      sven: 'スヴェン',
      tamarinne: 'ルリ',
      taranor_guard: 'タラノル近衛隊員',
      taranor_royal_guard: 'タラノル王宮衛兵',
      temmpest_surin: '風雲のスーリン',
      tenebria: 'テネブレア',
      tieria: 'ディエリア',
      troublemaker_crozet: '暴徒 クロゼ',
      tywin: 'タイウィン',
      vildred: 'ヴィルドレッド',
      violet: 'ヴィオレタ',
      vivian: 'ビビアン',
      wanda: 'ワンダ',
      wanderer_silk: '流浪者 シルク',
      watcher_schuri: '監視者 シュリ',
      yufine: 'ユピネ',
      yuna: 'ユナ',
      zeno: 'ゼノ',
      zerato: 'ゼラト',
    },
    nicknames: {
      achates: '',
      adlay: '',
      ains: '',
      aither: '',
      alencia: '',
      alexa: '',
      all_rounder_wanda: '',
      ambitious_tywin: '',
      angelic_montmorancy: '',
      angelica: '',
      apocalypse_ravi: '',
      aramintha: '',
      arbiter_vildred: '',
      armin: '',
      arowell: '',
      assassin_cartuja: '',
      assassin_cidd: '',
      assassin_coli: '',
      auxiliary_lots: '',
      azalea: '',
      baal_and_sezan: '',
      baiken: '',
      basar: '',
      bask: '',
      batisse: '',
      bellona: '',
      benevolent_romann: '',
      blaze_dingo: '',
      blood_blade_karin: '',
      butcher_corps_inquisitor: '',
      captain_rikoris: '',
      carmainerose: '',
      carrot: '',
      cartuja: '',
      cecilia: '',
      celeste: '',
      celestial_mercedes: '',
      cermia: '',
      challenger_dominiel: '',
      champion_zerato: '',
      chaos_inquisitor: '',
      chaos_sect_axe: '',
      charles: '',
      charlotte: '',
      chloe: '',
      church_of_ilryos_axe: '',
      cidd: '',
      clarissa: '',
      coli: '',
      commander_lorina: '',
      corvus: '',
      crescent_moon_rin: '',
      crimson_armin: '',
      crozet: '',
      dark_corvus: '',
      desert_jewel_basar: '',
      destina: '',
      diene: '',
      dingo: '',
      dizzy: '',
      dominiel: '',
      doris: '',
      eaton: '',
      elena: '',
      elson: '',
      enott: '',
      faithless_lidica: '',
      falconer_kluri: '',
      fallen_cecilia: '',
      fighter_maya: '',
      furious: '',
      general_purrgis: '',
      gloomyrain: '',
      guider_aither: '',
      gunther: '',
      hataan: '',
      haste: '',
      hazel: '',
      helga: '',
      hurado: '',
      iseria: '',
      jecht: '',
      jena: '',
      judge_kise: '',
      judith: '',
      karin: '',
      kayron: '',
      ken: '',
      khawana: '',
      khawazu: '',
      kiris: '',
      kise: '',
      kitty_clarissa: '',
      kluri: '',
      krau: '',
      lena: '',
      leo: '',
      lidica: '',
      lilias: '',
      lilibet: '',
      lorina: '',
      lots: '',
      ludwig: '',
      luluca: '',
      luna: '',
      maid_chloe: '',
      martial_artist_ken: '',
      mascot_hazel: '',
      maya: '',
      melissa: '',
      mercedes: '',
      mirsa: '',
      mistychain: '',
      montmorancy: '',
      mucacha: '',
      nemunas: '',
      otillie: '',
      pearlhorizon: '',
      purrgis: '',
      pyllis: '',
      ras: '',
      ravi: '',
      requiemroar: '',
      researcher_carrot: '',
      righteous_thief_roozid: '',
      rikoris: '',
      rima: '',
      rin: '',
      roaming_warrior_leo: '',
      roana: '',
      romann: '',
      roozid: '',
      rose: '',
      ruele_of_light: '',
      sage_baal_and_sezan: '',
      schuri: '',
      shooting_star_achates: '',
      seaside_bellona: '',
      serila: '',
      sez: '',
      shadow_rose: '',
      sigret: '',
      silk: '',
      silver_blade_aramintha: '',
      sinful_angelica: '',
      sol: '',
      specimen_sez: '',
      specter_tenebria: '',
      surin: '',
      sven: '',
      tamarinne: '',
      taranor_guard: '',
      taranor_royal_guard: '',
      tenebria: '',
      tieria: '',
      troublemaker_crozet: '',
      tywin: '',
      vildred: '',
      violet: '',
      vivian: '',
      wanda: '',
      wanderer_silk: '',
      watcher_schuri: '',
      yufine: '',
      yuna: '',
      zeno: '',
      zerato: '',
    },
    artifacts: {
      no_proc: '遺物効果なし',
      border_coin: '天命の金貨',
      daydream_joker: '白昼夢の道化師',
      dignus_orb: 'ディグヌスオーブ',
      draco_plate: 'ドラゴニックプレート',
      dux_noctis: 'ドゥクスノクティス',
      els_fist: 'エルの拳',
      exorcist_tonfa: '闘鬼の戦具',
      elyha_knife: 'エリハの短剣',
      hell_cutter: '地獄のチェーンソー',
      iron_fan: '高貴なる鉄扇',
      kaladra: 'カルラドラ',
      portrait_of_the_saviors: '英雄達の肖像',
      otherworldly_machinery: '異世界の機械',
      radiant_forever: '燦爛たる永遠',
      reingar_special_drink: 'レインガル特製ドリンク',
      sigurd_scythe: 'シグルの大鎌',
      sword_of_the_morning: '黎明の剣',
      tear_of_the_desert: '砂漠の涙',
      time_matter: '流転物質',
      uberius_tooth: 'ユーベリウスの牙',
      violet_talisman: "紫菫の輝き",
      wind_rider: '旋風の操手',
    },
    form: {
      nb_targets: '敵数',
      nb_hits: 'ヒット数',
      target_max_hp: 'ターゲットのの生命力上限値',
      target_hp_pc: 'ターゲットの生命力割合(%)',
      target_hp: 'ターゲットの生命力',
      target_speed: 'ターゲットのスピード',
      target_nb_buff: 'ターゲットのバフ数',
      target_nb_debuff: 'ターゲットのデバフ数',
      target_has_buff: 'ターゲットにバフあり',
      target_has_debuff: 'ターゲットにデバフあり',
      target_has_bleed: 'ターゲット出血状態',
      target_has_sleep: 'ターゲット睡眠状態',
      target_is_stunned: 'ターゲットスタン状態',
      target_has_barrier: 'ターゲットにバリアあり',
      target_magic_nailed: 'ターゲットに魔法釘デバフあり',
      target_nb_bleed: 'ターゲットの出血デバフ数',
      target_bleed_detonate: '出血激爆',
      target_burn_detonate: '火傷激爆',
      caster_max_hp: '自身の生命力上限値',
      caster_hp_pc: '自身の生命力割合(%)',
      caster_hp: '自身の生命力',
      caster_hp_above_50pc: '自身の生命力割合が50%以上',
      caster_defense: '自身の防御力',
      caster_defense_up: '自身に防御力UP',
      caster_speed: '自身のスピード',
      caster_speed_up: '自身にスピードUP',
      caster_nb_buff: '自身のバフ数',
      caster_full_focus: '集中MAX',
      caster_nb_focus: '集中',
      caster_fighting_spirit: '闘志',
      caster_invincible: '自身に無敵状態',
      caster_vigor: '自身に覇気バフあり',
      caster_enrage: '自身に狂気バフあり',
      caster_stealth: '自身に潜伏状態',
      critical_hit_stack: 'クリティカル発生回数',
      critical_hit_stack_12: 'クリティカル発生回数',
      non_attack_skill_stack_10: '攻撃ではないスキルの使用回数',
      attack_skill_stack_5: '累積攻撃回数',
      non_attack_skill_stack_3: '攻撃ではないスキルの使用回数',
      turn_stack: 'ターン経過回数',
      turn_stack_3: 'ターン経過回数',
      dead_people: '気絶中人数',
      highest_ally_attack: '最も攻撃力の高い味方の攻撃力',
      ally_atk_up: '味方に攻撃力UPバフあり',
      ally_atk_up_great: '味方に攻撃力UP（大）バフあり',
      skill_tree_completed: 'スキルツリーコンプリート',
      s3_stack: 'スキル3使用回数',
      all_allies_fire: '味方全員火属性',
      exclusive_equipment_1: '専用装備 #1',
      exclusive_equipment_2: '専用装備 #2',
      exclusive_equipment_3: '専用装備 #3',
    },
    skills: {
      non_applicable: 'n/a',
      s1: 'S1',
      s2: 'S2',
      s3: 'S3',
      s1_soulburn: 'S1 魂力解放',
      s2_soulburn: 'S2 魂力解放',
      s3_soulburn: 'S3 魂力解放',
    }
  },
  zhTW: {
    heroes: {
      achates: '雅卡泰絲',
      adlay: '亞迪賴',
      ains: '艾因茲',
      aither: '埃德勒',
      alencia: '艾蓮西雅',
      alexa: '雅莉莎',
      all_rounder_wanda: '疑難雜症專家汪達',
      ambitious_tywin: '野心份子泰溫',
      angelic_montmorancy: '守護天使蒙茉朗西',
      angelica: '安潔莉卡',
      apocalypse_ravi: '末日蘿菲',
      aramintha: '雅拉敏塔',
      arbiter_vildred: '執行官維德瑞',
      armin: '亞敏',
      arowell: '雅洛薇',
      assassin_cartuja: '殺手卡爾圖哈',
      assassin_cidd: '殺手席德',
      assassin_coli: '殺手可麗',
      auxiliary_lots: '輔助型拉茲',
      adventurer_ras: '冒險家拉斯',
      azalea: '亞潔理亞',
      baal_and_sezan: '巴爾&塞尚',
      baiken: '梅喧',
      basar: '巴薩爾',
      bask: '巴思克',
      batisse: '巴托斯',
      bellona: '維爾蘿娜',
      benevolent_romann: '仁慈的洛曼',
      blaze_dingo: '烈火汀果',
      blood_blade_karin: '血劍卡琳',
      blood_moon_haste: '赤月的貴族海斯特',
      butcher_corps_inquisitor: '混沌教屠殺追擊者',
      captain_rikoris: '先鋒隊長里科黎司',
      carmainerose: '卡麥蘿茲',
      carrot: '卡蘿',
      cartuja: '卡爾圖哈',
      cecilia: '賽西莉亞',
      celeste: '賽雷斯特',
      celestial_mercedes: '外太空的玫勒賽德絲',
      celine: '瑟琳',
      cerise: '賽瑞絲',
      cermia: '潔若米亞',
      challenger_dominiel: '挑戰者多米妮爾',
      champion_zerato: '終結者杰拉圖',
      chaos_inquisitor: '屠殺部隊員',
      chaos_sect_axe: '混沌教巨斧大將軍',
      charles: '查爾斯',
      charlotte: '夏綠蒂',
      chloe: '克蘿愛',
      church_of_ilryos_axe: '伊利歐斯教斧兵',
      cidd: '席德',
      clarissa: '克萊莉莎',
      coli: '可麗',
      commander_lorina: '指揮官蘿里娜',
      corvus: '科爾布思',
      crescent_moon_rin: '新月舞姬鈴兒',
      crimson_armin: '紅焰亞敏',
      crozet: '克羅澤',
      dark_corvus: '黑暗的科爾布思',
      desert_jewel_basar: '沙漠寶石巴薩爾',
      destina: '戴絲蒂娜',
      diene: '迪埃妮',
      dingo: '汀果',
      dizzy: '蒂姬',
      dominiel: '多米妮爾',
      doris: '朵莉思',
      eaton: '伊頓',
      elena: '艾蕾娜',
      elphelt_valentine: '愛爾菲特',
      elson: '艾爾森',
      enott: '艾諾特',
      faithless_lidica: '無神論者麗迪卡',
      falconer_kluri: '鷹獵人可露莉',
      fallen_cecilia: '墮落的賽西莉亞',
      fighter_maya: '戰鬥型瑪雅',
      free_spirit_tieria: '永恆不變的黛莉亞',
      furious: '尤貝烏斯',
      general_purrgis: '大將法濟斯',
      gloomyrain: '格魯美蘭',
      guider_aither: '求道者埃德勒',
      gunther: '坤特',
      hataan: '哈坦',
      haste: '海斯特',
      hazel: '海茲',
      helga: '赫爾嘉',
      hurado: '修拉杜',
      iseria: '伊賽麗亞',
      jecht: '傑克托',
      jena: '捷娜',
      judge_kise: '審判者綺世',
      judith: '茱迪絲',
      karin: '卡琳',
      kawerik: '卡威利',
      kayron: '凱隆',
      kizuna_ai: '絆愛',
      ken: '肯恩',
      khawana: '卡瓦娜',
      khawazu: '卡瓦朱',
      kikirat_v2: '奇奇拉特V.2',
      kiris: '奇麗絲',
      kise: '綺世',
      kitty_clarissa: '貓咪克萊莉莎',
      kluri: '可露莉',
      krau: '克勞烏',
      lena: '雷娜',
      leo: '雷歐',
      lidica: '麗迪卡',
      lilias: '莉莉亞斯',
      lilibet: '莉莉貝',
      little_queen_charlotte: '年輕的女王夏綠蒂',
      lorina: '蘿里娜',
      lots: '拉茲',
      ludwig: '魯特比',
      luluca: '璐璐卡',
      luna: '露娜',
      maid_chloe: '僕人克蘿愛',
      martial_artist_ken: '武鬥家肯恩',
      mascot_hazel: '吉祥物海茲',
      maya: '瑪雅',
      melissa: '梅麗莎',
      mercedes: '玫勒賽德絲',
      mercenary_helga: '自由自在的傭兵赫爾嘉',
      mighty_scout: '偵察兵瑪伊堤(木老鼠)',
      mirsa: '米勒莎',
      mistychain: '美絲緹彩',
      montmorancy: '蒙茉朗西',
      mucacha: '穆卡察',
      nemunas: '尼姆拉斯',
      otillie: '奧緹莉爾',
      pavel: '帕貝爾',
      pearlhorizon: '波蘿萊珍',
      purrgis: '法濟斯',
      pyllis: '費莉絲',
      ray: '雷伊',
      ras: '拉斯',
      ravi: '蘿菲',
      remnant_violet: '殘影的菲奧雷托',
      requiemroar: '雷奎姆洛',
      researcher_carrot: '研究者卡蘿',
      righteous_thief_roozid: '義賊魯茲德',
      rikoris: '里科黎司',
      rima: '黎瑪',
      rin: '鈴兒',
      roaming_warrior_leo: '流浪勇士雷歐',
      roana: '羅安納',
      romann: '洛曼',
      roozid: '魯茲德',
      rose: '蘿季',
      ruele_of_light: '光之瑞兒',
      sage_baal_and_sezan: '賢者巴爾&塞尚',
      schuri: '修里',
      shooting_star_achates: '流星雅卡泰絲',
      seaside_bellona: '海邊的維爾蘿娜',
      serila: '塞麗拉',
      sez: '賽茲',
      shadow_rose: '暗影蘿季',
      sigret: '賽珂蘭特',
      silk: '席可',
      silver_blade_aramintha: '白銀刀刃的雅拉敏塔',
      sinful_angelica: '罪戾的安潔莉卡',
      sol: '索爾',
      specimen_sez: '實驗體賽茲',
      specter_tenebria: '幻影的泰妮布里雅',
      surin: '蘇琳',
      sven: '史賓',
      tamarinne: '塔瑪林爾',
      taranor_guard: '塔拉諾爾禁衛隊員',
      taranor_royal_guard: '塔拉諾爾王宮士兵',
      temmpest_surin: '風雲蘇琳',
      tenebria: '泰妮布里雅',
      tieria: '黛莉亞',
      troublemaker_crozet: '不法之徒克羅澤',
      tywin: '泰溫',
      vildred: '維德瑞',
      violet: '菲奧雷托',
      vivian: '薇薇安',
      wanda: '汪達',
      wanderer_silk: '流浪者席可',
      watcher_schuri: '注視者修里',
      yufine: '優芬妮',
      yuna: '尤娜',
      zeno: '傑諾',
      zerato: '杰拉圖',
    },
    nicknames: {
      achates: '火奶',
      adlay: '',
      ains: '',
      aither: '小王子',
      alencia: '姨媽龍 龍姨媽',
      alexa: '小水刺',
      all_rounder_wanda: '轉職汪達',
      ambitious_tywin: '光泰溫',
      angelic_montmorancy: '包子頭 包包頭 小水奶',
      angelica: '大水奶 老太婆',
      apocalypse_ravi: '暗羅菲',
      aramintha: '火響指 火法',
      arbiter_vildred: '暗帝 暗25 暗弟',
      armin: '木敏 阿敏',
      arowell: '',
      assassin_cartuja: '暗熊',
      assassin_cidd: '暗席德',
      assassin_coli: '暗可麗',
      auxiliary_lots: '暗拉 暗拉茲',
      adventurer_ras: '男主 轉職男主',
      azalea: '',
      baal_and_sezan: '火三眼',
      baiken: '',
      basar: '埃及佬',
      bask: '',
      batisse: '小暗拳',
      bellona: '木扇',
      benevolent_romann: '光洛曼',
      blaze_dingo: '光廚子',
      blood_blade_karin: '血卡',
      blood_moon_haste: '暗正太',
      butcher_corps_inquisitor: '哥殺 哥布林殺手',
      captain_rikoris: '',
      carmainerose: '火爪',
      carrot: '卡羅',
      cartuja: '木熊',
      cecilia: '火龍騎',
      celeste: '三星光弓',
      celestial_mercedes: '暗女主',
      celine: '卡琳姨媽',
      cerise: '水弓',
      cermia: '夏娜',
      challenger_dominiel: '暗兔',
      champion_zerato: '暗傑 泥巴佬 泥巴哥',
      chaos_inquisitor: '',
      chaos_sect_axe: '暗斧',
      charles: '木老頭 劍聖',
      charlotte: '火呆毛 女王',
      chloe: '水錘',
      church_of_ilryos_axe: '',
      cidd: '木席德',
      clarissa: '水修女',
      coli: '水可麗',
      commander_lorina: '暗槍',
      corvus: '火老頭',
      crescent_moon_rin: '暗02 暗靈兒',
      crimson_armin: '光亞敏 光貓',
      crozet: '團長',
      dark_corvus: '魔神王 暗魔神',
      desert_jewel_basar: '光埃及',
      destina: '木奶',
      diene: '聖女',
      dingo: '火廚子',
      dizzy: 'DZ dizzy dz',
      dominiel: '冰兔',
      doris: '',
      eaton: '',
      elena: '水琴',
      elphelt_valentine: '火兔 兔槍',
      elson: '光正太',
      enott: '',
      faithless_lidica: '光弓 光高潮',
      falconer_kluri: '鷹盾 鳥盾',
      fallen_cecilia: '暗龍',
      fighter_maya: '光瑪雅',
      free_spirit_tieria: '',
      furious: '開水哥',
      general_purrgis: '光狗 狗大將',
      gloomyrain: '光爪',
      guider_aither: '光王子',
      gunther: '昆特 坤哥',
      hataan: '',
      haste: '火正太',
      hazel: '',
      helga: '三星小木斧',
      hurado: '光頭 三星暗法',
      iseria: '木飛劍',
      jecht: '木狗奶',
      jena: '',
      judge_kise: '光綺世 光74',
      judith: '小火刺',
      karin: '',
      kawerik: '威哥',
      kayron: '隆哥 凱寶',
      kizuna_ai: 'ai vtb',
      ken: '火拳',
      khawana: '火妹妹',
      khawazu: '',
      kikirat_v2: '高達 紮古 機器人',
      kiris: '毒弓',
      kise: '水74 新水鐮',
      kitty_clarissa: '暗貓',
      kluri: '',
      krau: '寶馬哥',
      lena: '水拳',
      leo: '木彈弓',
      lidica: '火弓 火高潮 高潮臉',
      lilias: 'llys 火盾',
      lilibet: '剪刀',
      little_queen_charlotte: '光呆毛',
      lorina: '',
      lots: '木拉茲 木拉',
      ludwig: '木正太',
      luluca: 'llk',
      luna: '水龍',
      maid_chloe: '光錘 光女仆',
      martial_artist_ken: '暗拳',
      mascot_hazel: '轉職火奶 腹黑',
      maya: '火瑪雅',
      melissa: '吸血鬼 孕婦',
      mercedes: '女主',
      mercenary_helga: '轉職木斧',
      mighty_scout: '木老鼠',
      mirsa: '三星小光刺',
      mistychain: '水爪',
      montmorancy: '',
      mucacha: '',
      nemunas: '',
      otillie: '',
      pavel: '木槍',
      pearlhorizon: '木爪',
      purrgis: '木狗 反擊狗',
      pyllis: '三星暗盾',
      ray: '男醫生',
      ras: '男主',
      ravi: '羅飛',
      remnant_violet: '暗蘋果 暗給 暗gay',
      requiemroar: '暗爪',
      researcher_carrot: '卡羅 轉職火法',
      righteous_thief_roozid: '木狗 拉條狗',
      rikoris: '',
      rima: '',
      rin: '木02',
      roaming_warrior_leo: '暗彈弓 暗炸彈',
      roana: '木瓜奶',
      romann: '羅曼',
      roozid: '',
      rose: '水蘿季 水羅 水羅季',
      ruele_of_light: '瑞兒 光奶',
      sage_baal_and_sezan: '光三眼',
      schuri: '火槍 火修',
      shooting_star_achates: 'SSA 暗奶 暗火奶',
      seaside_bellona: 'SSB 水扇',
      serila: '火南瓜',
      sez: '水刺',
      shadow_rose: '暗蘿季 暗羅季',
      sigret: '舊水鐮 眼鏡姐',
      silk: '木席可',
      silver_blade_aramintha: '光響指 光法',
      sinful_angelica: '暗水奶 暗奶',
      sol: 'sol',
      specimen_sez: '光刺',
      specter_tenebria: '暗法 暗泰妮',
      surin: '蘇林',
      sven: '屎兵',
      tamarinne: '偶像',
      taranor_guard: '水桶',
      taranor_royal_guard: '反擊水桶 反傷盾',
      temmpest_surin: '光蘇琳 光蘇林',
      tenebria: '泰妮 火泰妮 舊火法',
      tieria: '三星小火斧',
      troublemaker_crozet: '暗團長',
      tywin: '',
      vildred: '木刺 25仔',
      violet: '木給 木gay 木蘋果',
      vivian: 'vva',
      wanda: '',
      wanderer_silk: '光席可',
      watcher_schuri: '光修裏 光修理',
      yufine: '木龍',
      yuna: '學生會長',
      zeno: '',
      zerato: '水傑 冰傑 冰法',
    },
    artifacts: {
      no_proc: '無神器',
      border_coin: '孤注一擲',
      daydream_joker: '白日夢小丑',
      draco_plate: '龍族板甲',
      exorcist_tonfa: '鬥鬼的拐棍',
      elyha_knife: '埃里哈刀',
      hell_cutter: '地獄切割機',
      iron_fan: '鐵扇',
      kaladra: '嘉拉特拉',
      portrait_of_the_saviors: '救援者們的畫像',
      otherworldly_machinery: '異界的機械',
      reingar_special_drink: '雷茵格爾特調飲料',
      sigurd_scythe: '席格勒賽斯',
      sword_of_the_morning: '黎明劍',
      uberius_tooth: '尤貝里烏斯的臼齒',
      wind_rider: '乘風者',
      dux_noctis: '暗夜指揮者',
      els_fist: '艾爾之拳',
      dignus_orb: '尊嚴寶珠',
      tear_of_the_desert: '沙漠之淚',
      time_matter: '時間的物質',
      victorious_flag: '勝戰旗幟',
      violet_talisman: '紫色護身符',
      radiant_forever: '燦爛的永恆',
    },
    form: {
      nb_targets: '敵人數量',
      nb_hits: '攻擊次數',
      target_max_hp: '目標最大生命值',
      target_hp_pc: '目標當前生命值(%)',
      target_hp: '目標當前生命值',
      target_speed: '目標速度',
      target_nb_buff: '目標Buff數量',
      target_nb_debuff: '目標Debuff數量',
      target_has_buff: '目標有Buff',
      target_has_debuff: '目標有Debuff',
      target_has_bleed: '目標出血',
      target_has_sleep: '目標睡眠',
      target_is_stunned: '目標眩暈',
      target_has_barrier: '目標有防護罩',
      target_magic_nailed: '目標有魔法釘',
      target_nb_bleed: '目標出血Debuff數量',
      target_bleed_detonate: '出血Debuff回合數',
      target_burn_detonate: '燒傷Debuff回合數',
      caster_max_hp: '自身最大生命值',
      caster_hp_pc: '自身當前生命值(%)',
      caster_hp: '自身當前生命值',
      caster_hp_above_50pc: '自身當前生命值>50%',
      caster_defense: '自身防禦力',
      caster_defense_up: '防禦力增加',
      caster_speed: '自身速度',
      caster_speed_up: '速度提升',
      caster_nb_buff: '自身Buff數量',
      caster_full_focus: '專注力最大值',
      caster_nb_focus: '專注力',
      caster_fighting_spirit: '鬥志',
      caster_invincible: '自身無敵',
      caster_vigor: '自身魄力',
      caster_enrage: '自身激怒',
      caster_stealth: '自身隱身',
      critical_hit_stack: '暴擊叠加數',
      critical_hit_stack_12: '暴擊叠加數',
      non_attack_skill_stack_10: '非攻擊叠加數',
      attack_skill_stack_5: '攻擊叠加數',
      non_attack_skill_stack_3: '非攻擊叠加數',
      turn_stack: '回合叠加數',
      dead_people: '死亡人數',
      highest_ally_attack: '我軍最高攻擊力',
      ally_atk_up: '目標我軍攻擊力增加',
      ally_atk_up_great: '目標我軍攻擊力增加 (大幅)',
      skill_tree_completed: '技能樹滿覺醒',
      s3_stack: '3技能叠加數',
      all_allies_fire: '全體我軍火屬性',
      exclusive_equipment_1: '專屬裝備 #1',
      exclusive_equipment_2: '專屬裝備 #2',
      exclusive_equipment_3: '專屬裝備 #3',
    },
    skills: {
      non_applicable: '無',
      s1: '1技能',
      s2: '2技能',
      s3: '3技能',
      s1_soulburn: '1技能 靈魂燃燒',
      s2_soulburn: '2技能 靈魂燃燒',
      s3_soulburn: '3技能 靈魂燃燒',
    }
  },
  zhCN: {
    heroes: {
      achates: '雅卡泰丝',
      adlay: '亚迪赖',
      ains: '艾因兹',
      aither: '埃德勒',
      alencia: '艾莲西雅',
      alexa: '雅莉莎',
      all_rounder_wanda: '疑难杂症专家汪达',
      ambitious_tywin: '野心份子泰温',
      angelic_montmorancy: '守护天使蒙茉朗西',
      angelica: '安洁莉卡',
      apocalypse_ravi: '末日萝菲',
      aramintha: '雅拉敏塔',
      arbiter_vildred: '执行官维德瑞',
      armin: '亚敏',
      arowell: '雅洛薇',
      assassin_cartuja: '杀手卡尔图哈',
      assassin_cidd: '杀手席德',
      assassin_coli: '杀手可丽',
      auxiliary_lots: '辅助型拉兹',
      adventurer_ras: '冒险家拉斯',
      azalea: '亚洁理亚',
      baal_and_sezan: '巴尔&塞尚',
      baiken: '梅喧',
      basar: '巴萨尔',
      bask: '巴思克',
      batisse: '巴托斯',
      bellona: '维尔萝娜',
      benevolent_romann: '仁慈的洛曼',
      blaze_dingo: '烈火汀果',
      blood_blade_karin: '血剑卡琳',
      blood_moon_haste: '赤月的贵族海斯特',
      butcher_corps_inquisitor: '混沌教屠杀追击者',
      captain_rikoris: '先锋队长里科黎司',
      carmainerose: '卡麦萝兹',
      carrot: '卡萝',
      cartuja: '卡尔图哈',
      cecilia: '赛西莉亚',
      celeste: '赛雷斯特',
      celestial_mercedes: '外太空的玫勒赛德丝',
      celine: '瑟琳',
      cerise: '赛瑞丝',
      cermia: '洁若米亚',
      challenger_dominiel: '挑战者多米妮尔',
      champion_zerato: '终结者杰拉图',
      chaos_inquisitor: '屠杀部队员',
      chaos_sect_axe: '混沌教巨斧大将军',
      charles: '查尔斯',
      charlotte: '夏绿蒂',
      chloe: '克萝爱',
      church_of_ilryos_axe: '伊利欧斯教斧兵',
      cidd: '席德',
      clarissa: '克莱莉莎',
      coli: '可丽',
      commander_lorina: '指挥官萝里娜',
      corvus: '科尔布思',
      crescent_moon_rin: '新月舞姬铃儿',
      crimson_armin: '红焰亚敏',
      crozet: '克罗泽',
      dark_corvus: '黑暗的科尔布思',
      desert_jewel_basar: '沙漠宝石巴萨尔',
      destina: '戴丝蒂娜',
      diene: '迪埃妮',
      dingo: '汀果',
      dizzy: '蒂姬',
      dominiel: '多米妮尔',
      doris: '朵莉思',
      eaton: '伊顿',
      elena: '艾蕾娜',
      elphelt_valentine: '爱尔菲特',
      elson: '艾尔森',
      enott: '艾诺特',
      faithless_lidica: '无神论者丽迪卡',
      falconer_kluri: '鹰猎人可露莉',
      fallen_cecilia: '堕落的赛西莉亚',
      fighter_maya: '战斗型玛雅',
      free_spirit_tieria: '永恆不变的黛莉亚',
      furious: '尤贝乌斯',
      general_purrgis: '大将法济斯',
      gloomyrain: '格鲁美兰',
      guider_aither: '求道者埃德勒',
      gunther: '坤特',
      hataan: '哈坦',
      haste: '海斯特',
      hazel: '海兹',
      helga: '赫尔嘉',
      hurado: '修拉杜',
      iseria: '伊赛丽亚',
      jecht: '杰克托',
      jena: '捷娜',
      judge_kise: '审判者绮世',
      judith: '茱迪丝',
      karin: '卡琳',
      kawerik: '卡威利',
      kayron: '凯隆',
      kizuna_ai: '绊爱',
      ken: '肯恩',
      khawana: '卡瓦娜',
      khawazu: '卡瓦朱',
      kikirat_v2: '奇奇拉特V.2',
      kiris: '奇丽丝',
      kise: '绮世',
      kitty_clarissa: '猫咪克莱莉莎',
      kluri: '可露莉',
      krau: '克劳乌',
      lena: '雷娜',
      leo: '雷欧',
      lidica: '丽迪卡',
      lilias: '莉莉亚斯',
      lilibet: '莉莉贝',
      little_queen_charlotte: '年轻的女王夏绿蒂',
      lorina: '萝里娜',
      lots: '拉兹',
      ludwig: '鲁特比',
      luluca: '璐璐卡',
      luna: '露娜',
      maid_chloe: '仆人克萝爱',
      martial_artist_ken: '武斗家肯恩',
      mascot_hazel: '吉祥物海兹',
      maya: '玛雅',
      melissa: '梅丽莎',
      mercedes: '玫勒赛德丝',
      mercenary_helga: '自由自在的佣兵赫尔嘉',
      mighty_scout: '侦察兵玛伊堤(木老鼠)',
      mirsa: '米勒莎',
      mistychain: '美丝缇彩',
      montmorancy: '蒙茉朗西',
      mucacha: '穆卡察',
      nemunas: '尼姆拉斯',
      otillie: '奥缇莉尔',
      pavel: '帕贝尔',
      pearlhorizon: '波萝莱珍',
      purrgis: '法济斯',
      pyllis: '费莉丝',
      ray: '雷伊',
      ras: '拉斯',
      ravi: '萝菲',
      remnant_violet: '残影的菲奥雷托',
      requiemroar: '雷奎姆洛',
      researcher_carrot: '研究者卡萝',
      righteous_thief_roozid: '义贼鲁兹德',
      rikoris: '里科黎司',
      rima: '黎玛',
      rin: '铃儿',
      roaming_warrior_leo: '流浪勇士雷欧',
      roana: '罗安纳',
      romann: '洛曼',
      roozid: '鲁兹德',
      rose: '萝季',
      ruele_of_light: '光之瑞儿',
      sage_baal_and_sezan: '贤者巴尔&塞尚',
      schuri: '修里',
      shooting_star_achates: '流星雅卡泰丝',
      seaside_bellona: '海边的维尔萝娜',
      serila: '塞丽拉',
      sez: '赛兹',
      shadow_rose: '暗影萝季',
      sigret: '赛珂兰特',
      silk: '席可',
      silver_blade_aramintha: '白银刀刃的雅拉敏塔',
      sinful_angelica: '罪戾的安洁莉卡',
      sol: '索尔',
      specimen_sez: '实验体赛兹',
      specter_tenebria: '幻影的泰妮布里雅',
      surin: '苏琳',
      sven: '史宾',
      tamarinne: '塔玛林尔',
      taranor_guard: '塔拉诺尔禁卫队员',
      taranor_royal_guard: '塔拉诺尔王宫士兵',
      temmpest_surin: '风云苏琳',
      tenebria: '泰妮布里雅',
      tieria: '黛莉亚',
      troublemaker_crozet: '不法之徒克罗泽',
      tywin: '泰温',
      vildred: '维德瑞',
      violet: '菲奥雷托',
      vivian: '薇薇安',
      wanda: '汪达',
      wanderer_silk: '流浪者席可',
      watcher_schuri: '注视者修里',
      yufine: '优芬妮',
      yuna: '尤娜',
      zeno: '杰诺',
      zerato: '杰拉图',
    },
    nicknames: {
      achates: '火奶',
      adlay: '',
      ains: '',
      aither: '小王子',
      alencia: '姨妈龙 龙姨妈',
      alexa: '小水刺',
      all_rounder_wanda: '转职汪达',
      ambitious_tywin: '光泰温',
      angelic_montmorancy: '包子头 包包头 小水奶',
      angelica: '大水奶 老太婆',
      apocalypse_ravi: '暗罗菲',
      aramintha: '火响指 火法',
      arbiter_vildred: '暗帝 暗25 暗弟',
      armin: '木敏 阿敏',
      arowell: '',
      assassin_cartuja: '暗熊',
      assassin_cidd: '暗席德',
      assassin_coli: '暗可丽',
      auxiliary_lots: '暗拉 暗拉兹',
      adventurer_ras: '男主 转职男主',
      azalea: '',
      baal_and_sezan: '火三眼',
      baiken: '',
      basar: '埃及佬',
      bask: '',
      batisse: '小暗拳',
      bellona: '木扇',
      benevolent_romann: '光洛曼',
      blaze_dingo: '光厨子',
      blood_blade_karin: '血卡',
      blood_moon_haste: '暗正太',
      butcher_corps_inquisitor: '哥杀 哥布林杀手',
      captain_rikoris: '',
      carmainerose: '火爪',
      carrot: '卡罗',
      cartuja: '木熊',
      cecilia: '火龙骑',
      celeste: '三星光弓',
      celestial_mercedes: '暗女主',
      celine: '卡琳姨妈',
      cerise: '水弓',
      cermia: '夏娜',
      challenger_dominiel: '暗兔',
      champion_zerato: '暗杰 泥巴佬 泥巴哥',
      chaos_inquisitor: '',
      chaos_sect_axe: '暗斧',
      charles: '木老头 剑圣',
      charlotte: '火呆毛 女王',
      chloe: '水锤',
      church_of_ilryos_axe: '',
      cidd: '木席德',
      clarissa: '水修女',
      coli: '水可丽',
      commander_lorina: '暗枪',
      corvus: '火老头',
      crescent_moon_rin: '暗02 暗灵儿',
      crimson_armin: '光亚敏 光猫',
      crozet: '团长',
      dark_corvus: '魔神王 暗魔神',
      desert_jewel_basar: '光埃及',
      destina: '木奶',
      diene: '圣女',
      dingo: '火厨子',
      dizzy: 'DZ dizzy dz',
      dominiel: '冰兔',
      doris: '',
      eaton: '',
      elena: '水琴',
      elphelt_valentine: '火兔 兔枪',
      elson: '光正太',
      enott: '',
      faithless_lidica: '光弓 光高潮',
      falconer_kluri: '鹰盾 鸟盾',
      fallen_cecilia: '暗龙',
      fighter_maya: '光玛雅',
      free_spirit_tieria: '',
      furious: '开水哥',
      general_purrgis: '光狗 狗大将',
      gloomyrain: '光爪',
      guider_aither: '光王子',
      gunther: '昆特 坤哥',
      hataan: '',
      haste: '火正太',
      hazel: '',
      helga: '三星小木斧',
      hurado: '光头 三星暗法',
      iseria: '木飞剑',
      jecht: '木狗奶',
      jena: '',
      judge_kise: '光绮世 光74',
      judith: '小火刺',
      karin: '',
      kawerik: '威哥',
      kayron: '隆哥 凯宝',
      kizuna_ai: 'ai vtb',
      ken: '火拳',
      khawana: '火妹妹',
      khawazu: '',
      kikirat_v2: '高达 扎古 机器人',
      kiris: '毒弓',
      kise: '水74 新水镰',
      kitty_clarissa: '暗猫',
      kluri: '',
      krau: '宝马哥',
      lena: '水拳',
      leo: '木弹弓',
      lidica: '火弓 火高潮 高潮脸',
      lilias: 'llys 火盾',
      lilibet: '剪刀',
      little_queen_charlotte: '光呆毛',
      lorina: '',
      lots: '木拉兹 木拉',
      ludwig: '木正太',
      luluca: 'llk',
      luna: '水龙',
      maid_chloe: '光锤 光女仆',
      martial_artist_ken: '暗拳',
      mascot_hazel: '转职火奶 腹黑',
      maya: '火玛雅',
      melissa: '吸血鬼 孕妇',
      mercedes: '女主',
      mercenary_helga: '转职木斧',
      mighty_scout: '木老鼠',
      mirsa: '三星小光刺',
      mistychain: '水爪',
      montmorancy: '',
      mucacha: '',
      nemunas: '',
      otillie: '',
      pavel: '木枪',
      pearlhorizon: '木爪',
      purrgis: '木狗 反击狗',
      pyllis: '三星暗盾',
      ray: '男医生',
      ras: '男主',
      ravi: '罗飞',
      remnant_violet: '暗苹果 暗给 暗gay',
      requiemroar: '暗爪',
      researcher_carrot: '卡罗 转职火法',
      righteous_thief_roozid: '木狗 拉条狗',
      rikoris: '',
      rima: '',
      rin: '木02',
      roaming_warrior_leo: '暗弹弓 暗炸弹',
      roana: '木瓜奶',
      romann: '罗曼',
      roozid: '',
      rose: '水萝季 水罗 水罗季',
      ruele_of_light: '瑞儿 光奶',
      sage_baal_and_sezan: '光三眼',
      schuri: '火枪 火修',
      shooting_star_achates: 'SSA 暗奶 暗火奶',
      seaside_bellona: 'SSB 水扇',
      serila: '火南瓜',
      sez: '水刺',
      shadow_rose: '暗萝季 暗罗季',
      sigret: '旧水镰 眼镜姐',
      silk: '木席可',
      silver_blade_aramintha: '光响指 光法',
      sinful_angelica: '暗水奶 暗奶',
      sol: 'sol',
      specimen_sez: '光刺',
      specter_tenebria: '暗法 暗泰妮',
      surin: '苏林',
      sven: '屎兵',
      tamarinne: '偶像',
      taranor_guard: '水桶',
      taranor_royal_guard: '反击水桶 反伤盾',
      temmpest_surin: '光苏琳 光苏林',
      tenebria: '泰妮 火泰妮 旧火法',
      tieria: '三星小火斧',
      troublemaker_crozet: '暗团长',
      tywin: '',
      vildred: '木刺 25仔',
      violet: '木给 木gay 木苹果',
      vivian: 'vva',
      wanda: '',
      wanderer_silk: '光席可',
      watcher_schuri: '光修里 光修理',
      yufine: '木龙',
      yuna: '学生会长',
      zeno: '',
      zerato: '水杰 冰杰 冰法',
    },
    artifacts: {
      no_proc: '无神器',
      border_coin: '孤注一掷',
      daydream_joker: '白日梦小丑',
      draco_plate: '龙族板甲',
      exorcist_tonfa: '斗鬼的拐棍',
      elyha_knife: '埃里哈刀',
      hell_cutter: '地狱切割机',
      iron_fan: '铁扇',
      kaladra: '嘉拉特拉',
      portrait_of_the_saviors: '救援者们的画像',
      otherworldly_machinery: '异界的机械',
      reingar_special_drink: '雷茵格尔特调饮料',
      sigurd_scythe: '席格勒赛斯',
      sword_of_the_morning: '黎明剑',
      uberius_tooth: '尤贝里乌斯的臼齿',
      wind_rider: '乘风者',
      dux_noctis: '暗夜指挥者',
      els_fist: '艾尔之拳',
      dignus_orb: '尊严宝珠',
      tear_of_the_desert: '沙漠之泪',
      time_matter: '时间的物质',
      victorious_flag: '胜战旗帜',
      violet_talisman: '紫色护身符',
      radiant_forever: '灿烂的永恆',
    },
    form: {
      nb_targets: '敌人数量',
      nb_hits: '攻击次数',
      target_max_hp: '目标最大生命值',
      target_hp_pc: '目标当前生命值(%)',
      target_hp: '目标当前生命值',
      target_speed: '目标速度',
      target_nb_buff: '目标Buff数量',
      target_nb_debuff: '目标Debuff数量',
      target_has_buff: '目标有Buff',
      target_has_debuff: '目标有Debuff',
      target_has_bleed: '目标出血',
      target_has_sleep: '目标睡眠',
      target_is_stunned: '目标眩晕',
      target_has_barrier: '目标有防护罩',
      target_magic_nailed: '目标有魔法钉',
      target_nb_bleed: '目标出血Debuff数量',
      target_bleed_detonate: '出血Debuff回合数',
      target_burn_detonate: '烧伤Debuff回合数',
      caster_max_hp: '自身最大生命值',
      caster_hp_pc: '自身当前生命值(%)',
      caster_hp: '自身当前生命值',
      caster_hp_above_50pc: '自身当前生命值>50%',
      caster_defense: '自身防御力',
      caster_defense_up: '防御力增加',
      caster_speed: '自身速度',
      caster_speed_up: '速度提升',
      caster_nb_buff: '自身Buff数量',
      caster_full_focus: '专注力最大值',
      caster_nb_focus: '专注力',
      caster_fighting_spirit: '斗志',
      caster_invincible: '自身无敌',
      caster_vigor: '自身魄力',
      caster_enrage: '自身激怒',
      caster_stealth: '自身隐身',
      critical_hit_stack: '暴击叠加数',
      critical_hit_stack_12: '暴击叠加数',
      non_attack_skill_stack_10: '非攻击叠加数',
      attack_skill_stack_5: '攻击叠加数',
      non_attack_skill_stack_3: '非攻击叠加数',
      turn_stack: '回合叠加数',
      dead_people: '死亡人数',
      highest_ally_attack: '我军最高攻击力',
      ally_atk_up: '目标我军攻击力增加',
      ally_atk_up_great: '目标我军攻击力增加 (大幅)',
      skill_tree_completed: '技能树满觉醒',
      s3_stack: '3技能叠加数',
      all_allies_fire: '全体我军火属性',
      exclusive_equipment_1: '专属装备 #1',
      exclusive_equipment_2: '专属装备 #2',
      exclusive_equipment_3: '专属装备 #3',
    },
    skills: {
      non_applicable: '无',
      s1: '1技能',
      s2: '2技能',
      s3: '3技能',
      s1_soulburn: '1技能 灵魂燃烧',
      s2_soulburn: '2技能 灵魂燃烧',
      s3_soulburn: '3技能 灵魂燃烧',
    }
  },
  kr: {
    heroes: {
      achates: '아카테스',
      adlay: '아들라이',
      adventurer_ras: '모험가 라스',
      ains: '에인즈',
      aither: '아이테르',
      alencia: '알렌시아',
      alexa: '알렉사',
      all_rounder_wanda: '만능 해결사 완다',
      ambitious_tywin: '야심가 타이윈',
      angelic_montmorancy: '수호천사 몽모랑시',
      angelica: '안젤리카',
      apocalypse_ravi: '화란의 라비',
      aramintha: '아라민타',
      arbiter_vildred: '집행관 빌트레드',
      armin: '아밍',
      arowell: '아로웰',
      assassin_cartuja: '암살자 카르투하',
      assassin_cidd: '암살자 시더',
      assassin_coli: '암살자 콜리',
      auxiliary_lots: '보조형 랏츠',
      azalea: '아젤리아',
      baal_and_sezan: '바알 & 세잔',
      baiken: '바이켄',
      basar: '바사르',
      bask: '바스크',
      batisse: '바터스',
      bellona: '벨로나',
      benevolent_romann: '자애의 로만',
      blaze_dingo: '열화의 딩고',
      blood_blade_karin: '혈검 카린',
      blood_moon_haste: '적월의 귀족 헤이스트',
      butcher_corps_inquisitor: '카오스교 도살추적자',
      captain_rikoris: '선봉대장 리코리스',
      carmainerose: '카마인로즈',
      carrot: '캐롯',
      cartuja: '카르투하',
      cecilia: '세실리아',
      celeste: '셀레스트',
      celestial_mercedes: '외우주의 메르세데스',
      celine: '셀린',
      cerise: '세리스',
      cermia: '체르미아',
      challenger_dominiel: '도전자 도미니엘',
      champion_zerato: '승부의 제라토',
      chaos_inquisitor: '도살부대원',
      chaos_sect_axe: '카오스교 도끼 대장군',
      charles: '찰스',
      charlotte: '샬롯',
      chloe: '클로에',
      church_of_ilryos_axe: '일리오스교 도끼병',
      cidd: '시더',
      clarissa: '클라릿사',
      coli: '콜리',
      commander_lorina: '지휘관 로리나',
      corvus: '코르부스',
      crescent_moon_rin: '초승달 무희 링',
      crimson_armin: '홍염의 아밍',
      crozet: '크로제',
      dark_corvus: '어둠의 코르부스',
      desert_jewel_basar: '사막의 보석 바사르',
      destina: '데스티나',
      diene: '디에네',
      dingo: '딩고',
      dizzy: '디지',
      dominiel: '도미니엘',
      doris: '도리스',
      eaton: '이튼',
      elena: '엘레나',
      elphelt_valentine: '엘페르트 발렌타인',
      elson: '엘슨',
      enott: '에노트',
      faithless_lidica: '불신자 리디카',
      falconer_kluri: '매사냥꾼 쿠루리',
      fallen_cecilia: '나락의 세실리아',
      fighter_maya: '전투형 마야',
      free_spirit_tieria: '여일의 디에리아',
      furious: '퓨리우스',
      general_purrgis: '대장 퍼지스',
      gloomyrain: '글루미레인',
      guider_aither: '구도자 아이테르',
      gunther: '군터',
      hataan: '하탄',
      haste: '헤이스트',
      hazel: '헤이즐',
      helga: '헬가',
      hurado: '휴라두',
      iseria: '이세리아',
      jecht: '제크토',
      jena: '제나',
      judge_kise: '심판자 키세',
      judith: '쥬디스',
      karin: '카린',
      kawerik: '카웨릭',
      kayron: '카일론',
      ken: '켄',
      khawana: '카와나',
      khawazu: '카와주',
      kikirat_v2: '키키라트 v2',
      kiris: '키리스',
      kise: '키세',
      kitty_clarissa: '고양이 클라릿사',
      kizuna_ai: '키즈나 아이',
      kluri: '쿠루리',
      krau: '크라우',
      lena: '레나',
      leo: '레오',
      lidica: '리디카',
      lilias: '릴리아스',
      lilibet: '릴리벳',
      little_queen_charlotte: '어린 여왕 샬롯',
      lorina: '로리나',
      lots: '랏츠',
      ludwig: '루트비히',
      luluca: '루루카',
      luna: '루나',
      maid_chloe: '메이드 클로에',
      martial_artist_ken: '무투가 켄',
      mascot_hazel: '마스코트 헤이즐',
      maya: '마야',
      melissa: '멜리사',
      mercedes: '메르세데스',
      mercenary_helga: '자유로운 용병 헬가',
      mirsa: '미르사',
      mistychain: '미스티체인',
      montmorancy: '몽모랑시',
      mucacha: '무카차',
      nemunas: '네무나스',
      otillie: '오틸리어',
      pavel: '파벨',
      pearlhorizon: '펄호라이즌',
      purrgis: '퍼지스',
      pyllis: '필리스',
      ras: '라스',
      ravi: '라비',
      ray: '레이',
      remnant_violet: '잔영의 비올레토',
      requiemroar: '레퀴엠로어',
      researcher_carrot: '연구자 캐롯',
      righteous_thief_roozid: '의적 루지드',
      rikoris: '리코리스',
      rima: '리마',
      rin: '링',
      roaming_warrior_leo: '방랑 용사 레오',
      roana: '로앤나',
      romann: '로만',
      roozid: '루지드',
      rose: '로제',
      ruele_of_light: '빛의 루엘',
      sage_baal_and_sezan: '현자 바알 & 세잔',
      schuri: '슈리',
      seaside_bellona: '해변의 벨로나',
      serila: '세릴라',
      sez: '세즈',
      sinful_angelica: '죄악의 안젤리카',
      shadow_rose: '그림자 로제',
      shooting_star_achates: '슈팅스타 아카테스',
      sigret: '세크레트',
      silk: '실크',
      silver_blade_aramintha: '백은칼날의 아라민타',
      sol: '솔',
      specimen_sez: '실험체 세즈',
      specter_tenebria: '환영의 테네브리아',
      surin: '수린',
      sven: '스벤',
      tamarinne: '타마린느',
      taranor_guard: '타라노르 근위부대원',
      taranor_royal_guard: '타라노르 왕궁병사',
      temmpest_surin: '풍운의 수린',
      tenebria: '테네브리아',
      tieria: '디에리아',
      troublemaker_crozet: '무법자 크로제',
      tywin: '타이윈',
      vildred: '빌트레드',
      violet: '비올레토',
      vivian: '비비안',
      wanda: '완다',
      wanderer_silk: '방랑자 실크',
      watcher_schuri: '주시자 슈리',
      yufine: '유피네',
      yuna: '유나',
      zeno: '제노',
      zerato: '제라토',
    },
    nicknames: {
      achates: '',
      adlay: '',
      ains: '',
      aither: '',
      alencia: '',
      alexa: '',
      all_rounder_wanda: '',
      ambitious_tywin: '',
      angelic_montmorancy: '',
      angelica: '',
      apocalypse_ravi: '',
      aramintha: '',
      arbiter_vildred: '',
      armin: '',
      arowell: '',
      assassin_cartuja: '',
      assassin_cidd: '',
      assassin_coli: '',
      auxiliary_lots: '',
      azalea: '',
      baal_and_sezan: '',
      baiken: '',
      basar: '',
      bask: '',
      batisse: '',
      bellona: '',
      benevolent_romann: '',
      blaze_dingo: '',
      blood_blade_karin: '',
      butcher_corps_inquisitor: '',
      captain_rikoris: '',
      carmainerose: '',
      carrot: '',
      cartuja: '',
      cecilia: '',
      celeste: '',
      celestial_mercedes: '',
      cermia: '',
      challenger_dominiel: '',
      champion_zerato: '',
      chaos_inquisitor: '',
      chaos_sect_axe: '',
      charles: '',
      charlotte: '',
      chloe: '',
      church_of_ilryos_axe: '',
      cidd: '',
      clarissa: '',
      coli: '',
      commander_lorina: '',
      corvus: '',
      crescent_moon_rin: '',
      crimson_armin: '',
      crozet: '',
      dark_corvus: '',
      desert_jewel_basar: '',
      destina: '',
      diene: '',
      dingo: '',
      dizzy: '',
      dominiel: '',
      doris: '',
      eaton: '',
      elena: '',
      elson: '',
      enott: '',
      faithless_lidica: '',
      falconer_kluri: '',
      fallen_cecilia: '',
      fighter_maya: '',
      furious: '',
      general_purrgis: '',
      gloomyrain: '',
      guider_aither: '',
      gunther: '',
      hataan: '',
      haste: '',
      hazel: '',
      helga: '',
      hurado: '',
      iseria: '',
      jecht: '',
      jena: '',
      judge_kise: '',
      judith: '',
      karin: '',
      kayron: '',
      ken: '',
      khawana: '',
      khawazu: '',
      kiris: '',
      kise: '',
      kitty_clarissa: '',
      kluri: '',
      krau: '',
      lena: '',
      leo: '',
      lidica: '',
      lilias: '',
      lilibet: '',
      lorina: '',
      lots: '',
      ludwig: '',
      luluca: '',
      luna: '',
      maid_chloe: '',
      martial_artist_ken: '',
      mascot_hazel: '',
      maya: '',
      melissa: '',
      mercedes: '',
      mirsa: '',
      mistychain: '',
      montmorancy: '',
      mucacha: '',
      nemunas: '',
      otillie: '',
      pearlhorizon: '',
      purrgis: '',
      pyllis: '',
      ras: '',
      ravi: '',
      requiemroar: '',
      researcher_carrot: '',
      righteous_thief_roozid: '',
      rikoris: '',
      rima: '',
      rin: '',
      roaming_warrior_leo: '',
      roana: '',
      romann: '',
      roozid: '',
      rose: '',
      ruele_of_light: '',
      sage_baal_and_sezan: '',
      schuri: '',
      shooting_star_achates: '',
      seaside_bellona: '',
      serila: '',
      sez: '',
      shadow_rose: '',
      sigret: '',
      silk: '',
      silver_blade_aramintha: '',
      sinful_angelica: '',
      sol: '',
      specimen_sez: '',
      specter_tenebria: '',
      surin: '',
      sven: '',
      tamarinne: '',
      taranor_guard: '',
      taranor_royal_guard: '',
      tenebria: '',
      tieria: '',
      troublemaker_crozet: '',
      tywin: '',
      vildred: '',
      violet: '',
      vivian: '',
      wanda: '',
      wanderer_silk: '',
      watcher_schuri: '',
      yufine: '',
      yuna: '',
      zeno: '',
      zerato: '',
    },
    artifacts: {
      no_proc: '아티팩트 효과 없음',
      border_coin: '경계의 금화',
      daydream_joker: '데이드림 조커',
      dignus_orb: '디그누스 오브',
      draco_plate: '드라고니언 플레이트',
      dux_noctis: '둑스 녹티스',
      els_fist: '엘의 주먹',
      exorcist_tonfa: '투귀의 톤파',
      elyha_knife: '엘리하 나이프',
      hell_cutter: '지옥 절단기',
      iron_fan: '철선',
      kaladra: '칼라드라',
      portrait_of_the_saviors: '구원자의 초상화',
      otherworldly_machinery: '이세계의 머서너리',
      radiant_forever: '찬란한 영원',
      reingar_special_drink: '레인가르 특제 음료수',
      sigurd_scythe: '시구르사이즈',
      sword_of_the_morning: '여명의 검',
      tear_of_the_desert: '사막의 눈물',
      time_matter: '시간의 물질',
      uberius_tooth: '유베리우스의 어금니',
      violet_talisman: "보랏빛 탈리스만",
      wind_rider: '윈드라이더',
    },
    form: {
      nb_targets: '대상 수',
      nb_hits: '히트 수',
      target_max_hp: '대상의 최대 생명력',
      target_hp_pc: '대상의 생명력 비례(%)',
      target_hp: '대상의 생명력',
      target_speed: '대상의 속도',
      target_nb_buff: '대상의 강화효과 개수',
      target_nb_debuff: '대상의 약화효과 개수',
      target_has_buff: '대상에게 강화효과가 있음',
      target_has_debuff: '대상에게 약화효과가 있음',
      target_has_bleed: '대상에게 출혈효과가 있음',
      target_has_sleep: '대상이 수면상태',
      target_is_stunned: '대상이 기절상태',
      target_has_barrier: '대상에게 보호막이 있음',
      target_magic_nailed: '대상에게 마법못이 있음',
      target_nb_bleed: '대상이 가진 출혈효과 개수',
      target_bleed_detonate: '격폭 (출혈)',
      target_burn_detonate: '격폭 (화상)',
      caster_max_hp: '시전자의 최대 생명력',
      caster_hp_pc: '현재 생명력 비율',
      caster_hp: '시전자의 생명력',
      caster_hp_above_50pc: '생명력 절반 이상',
      caster_defense: '방어력',
      caster_defense_up: '방어력 증가',
      caster_speed: '시전자의 속도',
      caster_speed_up: '속도 증가',
      caster_nb_buff: '강화효과 수',
      caster_full_focus: '풀 집중',
      caster_nb_focus: '집중',
      caster_fighting_spirit: '패기',
      caster_invincible: '무적',
      caster_vigor: '패기',
      caster_enrage: '분노',
      caster_stealth: '은신',
      critical_hit_stack: '치명피해 스택',
      critical_hit_stack_12: '치명피해 스택',
      non_attack_skill_stack_10: '비공격 스킬 스택',
      attack_skill_stack_5: '공격 스택',
      non_attack_skill_stack_3: '비공격 스킬 스택',
      turn_stack: '턴 스택',
      turn_stack_3: '턴 스택',
      dead_people: '사망자',
      highest_ally_attack: '아군의 가장 높은 공격력',
      ally_atk_up: '아군 공격력 증가',
      ally_atk_up_great: '아군 공격력 증가 (대)',
      skill_tree_completed: 'Skill Tree Completed',
      s3_stack: '3스킬 스택',
      all_allies_fire: '모든 아군이 화염속성',
      exclusive_equipment_1: '전용장비 #1',
      exclusive_equipment_2: '전용장비 #2',
      exclusive_equipment_3: '전용장비 #3',
    },
    skills: {
      non_applicable: '해당사항 없음',
      s1: '스킬 1',
      s2: '스킬 2',
      s3: '스킬 3',
      s1_soulburn: '스킬 1 소울번', // usually, a short term for (스킬 n) is (n스)
      s2_soulburn: '스킬 2 소울번',
      s3_soulburn: '스킬 3 소울번',
    }
  }
};

const heroName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return heroes[id].name;
  } else {
    return i18n[lang].heroes[id] || heroes[id].name;
  }
};

const heroNickname = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  return i18n[lang].nicknames[id] || '';
};

const artifactName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return artifacts[id] ? artifacts[id].name : 'No Artifact Proc';
  } else {
    return i18n[lang].artifacts[id || 'no_proc'] || artifacts[id].name;
  }
};

const formLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return elements[id].label;
  } else {
    return i18n[lang].form[id] || elements[id].label;
  }
};

const skillLabel = (id, soulburn = false) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return (id === 'non_applicable') ? 'n/a' : id.toUpperCase() + (soulburn ? ' Soulburn' : '');
  } else {
    id = soulburn ? id+'_soulburn' : id;
    return i18n[lang].skills[id] || id.toUpperCase();
  }
};

const compareSkillLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  const idSplit = id.split('_');
  id = idSplit[0];
  const extra = idSplit[1] || '';

  let display;
  if (lang === 'en') {
    display = id.toUpperCase();
  } else {
    display = i18n[lang].skills[id] || id.toUpperCase();
  }

  if (extra === 'sb') {
    display += '<i class="fas fa-fire"></i>';
  } else if (extra!== '') {
    display += '<i class="far fa-plus-square"></i>';
  }

  return display
};